/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as LeistungenRouteImport } from './routes/leistungen'
import { Route as UeberMichRouteImport } from './routes/ueber-mich'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as EnAboutRouteImport } from './routes/en/about'
import { Route as EnContactRouteImport } from './routes/en/contact'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenRoute = LeistungenRouteImport.update({
  id: '/leistungen',
  path: '/leistungen',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberMichRoute = UeberMichRouteImport.update({
  id: '/ueber-mich',
  path: '/ueber-mich',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/en/about',
  path: '/en/about',
  getParentRoute: () => rootRouteImport,
} as any)
const EnContactRoute = EnContactRouteImport.update({
  id: '/en/contact',
  path: '/en/contact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/ueber-mich': typeof UeberMichRoute
  '/en/about': typeof EnAboutRoute
  '/en/contact': typeof EnContactRoute
  '/en/': typeof EnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/ueber-mich': typeof UeberMichRoute
  '/en/about': typeof EnAboutRoute
  '/en/contact': typeof EnContactRoute
  '/en': typeof EnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/ueber-mich': typeof UeberMichRoute
  '/en/about': typeof EnAboutRoute
  '/en/contact': typeof EnContactRoute
  '/en/': typeof EnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/leistungen'
    | '/ueber-mich'
    | '/en/about'
    | '/en/contact'
    | '/en/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/leistungen'
    | '/ueber-mich'
    | '/en/about'
    | '/en/contact'
    | '/en'
  id:
    | '__root__'
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/leistungen'
    | '/ueber-mich'
    | '/en/about'
    | '/en/contact'
    | '/en/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  LeistungenRoute: typeof LeistungenRoute
  UeberMichRoute: typeof UeberMichRoute
  EnAboutRoute: typeof EnAboutRoute
  EnContactRoute: typeof EnContactRoute
  EnIndexRoute: typeof EnIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen': {
      id: '/leistungen'
      path: '/leistungen'
      fullPath: '/leistungen'
      preLoaderRoute: typeof LeistungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber-mich': {
      id: '/ueber-mich'
      path: '/ueber-mich'
      fullPath: '/ueber-mich'
      preLoaderRoute: typeof UeberMichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/about': {
      id: '/en/about'
      path: '/en/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/contact': {
      id: '/en/contact'
      path: '/en/contact'
      fullPath: '/en/contact'
      preLoaderRoute: typeof EnContactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  LeistungenRoute: LeistungenRoute,
  UeberMichRoute: UeberMichRoute,
  EnAboutRoute: EnAboutRoute,
  EnContactRoute: EnContactRoute,
  EnIndexRoute: EnIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
